### ISSUE TITLE
批量替换处理的时候会报错deferred timeout······

### ISSUE THREAD

**Issue by YangWaldon** [sethyuan/logseq-plugin-batch-op#1]
![image](https://user-images.githubusercontent.com/49675185/185890796-f9ae5348-53b6-4e0e-a80a-aef5d27b1e9c.png)

**Comment by sethyuan** [comment]
看起来是有操作超时了，我排查下看怎么处理。

**Comment by sethyuan** [comment]
我调整了一下实现逻辑并发布了新版本，希望可以解决问题。你试试看呢。

**Comment by sethyuan** [comment]
好的，那我先将这个ticket关了。
