### ISSUE TITLE
Icon not showing up in Top-Bar in 0.8.2

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-batch-op#2]
The icon does not show up on macOS Logseq version 0.8.2 and [logseq-plugin-batch-op](https://github.com/sethyuan/logseq-plugin-batch-op) version 0.2.1

Updated Logseq from 0.8.1 and then after restart updatedlogseq-plugin-batch-op to latest.

Icon gone and not in list with pushpins under Plugin Icon
restarted Logseq
same issue

reindexed / reloaded -> working again!

Reported as reference for others

**Comment by sethyuan** [comment]
For the record, you can also access the plugin via the command palette (`ctrl+shift+p` or `cmd+shift+p`),
