### ISSUE TITLE
一个需求: 增加批量复制块引用的选项

### ISSUE THREAD

**Issue by YangWaldon** [sethyuan/logseq-plugin-batch-op#3]
由于logseq自带的搜索中，无法对搜索结果进行批量复制引用的操作，所以就想寄希望于这个强大的插件。虽然这个插件的查询结果中，有**id:: ······**这个属性，但是如果想要批量将id复制成**((id))**的形式的话，还是需要废一番周折的，所以希望开发者能加一个这样的功能，有这种需求的人应该还挺多的

**Comment by sethyuan** [comment]
能给个例子吗？我不确定你想要实现的效果是什么样子的。

**Comment by YangWaldon** [comment]
![image](https://user-images.githubusercontent.com/49675185/188757069-d1d8aa31-b29c-443f-ab8a-1ae66a10cc46.png)
![image](https://user-images.githubusercontent.com/49675185/188757083-fe028270-efea-4a3c-93af-a420e7f97a2c.png)
![image](https://user-images.githubusercontent.com/49675185/188757094-13a89c74-3402-4ff7-b53a-d3e79164c769.png)

**Comment by sethyuan** [comment]
能否提供一个实际的使用场景？什么时候会有这种需要呢？

**Comment by YangWaldon** [comment]
比如当我在写一条新的笔记的时候，想起来之前好像记录过与该条比较相关的内容。于是就通过搜索来查询之前的笔记，有相关性的就可以通过block id 的方式引用过来，通过综合对比分析，就能加深理解程度。

**Comment by sethyuan** [comment]
这个场景的话直接键入 `((` 查找是不是更方便？

**Comment by YangWaldon** [comment]
当相关的笔记多的时候，我感觉这种方式并不方便，每次选中一个之后，都需要再次((，需要在众多的结果中再次筛选出一个，然后再次((，再筛选出一个，不但效率低下，而且极为耗神

**Comment by sethyuan** [comment]
感觉用本插件也不是很适合。也许你可以在右侧边栏插入一个查询，然后再把想要的block引用拷贝过去。
