### ISSUE TITLE
大佬！属性增加时，遇到同名属性，能否直接在后面增加？

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-batch-op#6]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/107061250/220511861-2a2f1f9c-4e48-4f0b-a45e-566f0008de41.png">

**Comment by sethyuan** [comment]
如果这样实现的话就做不到想覆盖的场景了。也许可以追加一个checkbox，勾上就代表追加，否则还是默认的覆盖。

**Comment by hillsmao** [comment]
> 如果这样实现的话就做不到想覆盖的场景了。也许可以追加一个checkbox，勾上就代表追加，否则还是默认的覆盖。

嗯嗯，我这段时间在整理我那13000个页面。。场景是，搜索“[[半山坡]]”，出来几十个结果，我想把它们增加一个 #中年 的标签，不知道从哪里增加，只好增加一行属性 tags:: #中年；但有一些块已经有 tags:: 属性了，结果就被覆盖了。

**Comment by sethyuan** [comment]
@hillsmao ，目前可以用正则替换来实现追加，下面是一个示例，你根据你的具体场景调整一下吧。

![image](https://user-images.githubusercontent.com/3410293/221101753-ea3710b2-7fd5-4a7f-bef3-01d6e4fefaf1.png)

**Comment by hillsmao** [comment]
so cool！
