### ISSUE TITLE
还有就是，能不能做到上下文的搜索？

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-batch-op#7]
例如：  我有一个  #选题 的标签，在block中的结构是这样的：

#选题
-- 题目

我想改成

题目
type:: #选题

有可能吗？

**Comment by sethyuan** [comment]
改变结构的操作是支持不了的，这个有点难，因为改法太多了。

**Comment by hillsmao** [comment]
好的，我再琢磨琢磨
